config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'static_pages#top'
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/v1/auth/registrations',
    sessions: 'api/v1/auth/sessions'
  }
  devise_scope :user do
    post 'auth/guest_sign_in', to: 'api/v1/auth/sessions#guest_sign_in'
  end
  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show create] do
        get :search, on: :collection
      end
      resources :postings, only: %i[index show update destroy]
      resources :likes, only: %i[index create destroy] do 
        get :favorites, on: :collection
      end
      resources :comments, only: %i[index create update destroy]
      resource :profiles, only: %i[] do
        get :mypage, on: :collection
        get '/:username', to: 'profiles#show'
      end
    end
  end

  devise_for :admins, skip: %i[registrations passoword], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :posts
    resources :comments
  end

  get '*path', to: 'static_pages#top'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  user_id    :bigint           not null
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
  # scope :filter_by_post, ->(post_id) { where(post_id:) if post_id }
end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < Admins::BaseController
  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @comments = Comment.all.order(updated_at: :desc).includes(%i[user post]).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to admins_comment_path(@comment), success: t('defaults.message.updated', item: Comment.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Comment.model_name.human)
      render :edit
    end
  end

  def destroy
    @comment.destroy!
    redirect_to admins_comments_path(@comment), success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  before_action :authenticate_user!, only: %i[create update destroy]
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.includes(%i[user post]).order(created_at: :desc)
    # @comments = Comment.filter_by_post(params[:post_id]).includes(%i[user post]).order(updated_at: :asc)
    @user = current_user
    render :index, formats: :json, handlers: 'jbuilder'
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      render json: @comment, status: :ok
    else
      render @comment.errors, status: :bad_request
    end
  end

  def update
    @comment = current_user.comments.find(params[:id])
    if @comment.update(update_params)
      render json: @comment, status: :ok
    else
      render json: @comment.errors, status: :ok
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    if @comment.destroy
      render json: @comment, status: :ok
    else
      render json: @comment.errors, status: :bad_request
    end
  end

  private

  def comment_params
    params.permit(:post_id, :body)
  end

  def update_params
    params.permit(:body)
  end
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/views/admins/comments/_comment.html.erb
<tr>
  <td>
    <%= comment.id %>
  </td>
  <td>
    <%= comment.post.title %>
  </td>
  <td>
    <%= comment.user.name %>
  </td>
  <td>
    <%= l comment.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admins_comment_path(comment), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admins_comment_path(comment), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admins_comment_path(comment), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admins/comments/destroy.html.erb
<h1>Admins::Comments#destroy</h1>
<p>Find me in app/views/admins/comments/destroy.html.erb</p>

app/views/admins/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= form_with model: @comment, url: admins_comment_path(@comment), local: true do |f| %>
      <%= render 'admins/shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_field :body, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/comments/index.html.erb
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col"><%= Comment.human_attribute_name(:id) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:post) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:user) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:created_at) %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @comments %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @comments %>
    </div>
  </div>
</div>

app/views/admins/comments/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admins_comment_path(@comment), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admins_comment_path(@comment), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <!-- コメント内容 -->
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Comment.human_attribute_name(:id) %></th>
          <td><%= @comment.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Comment.human_attribute_name(:post) %></th>
          <td><%= @comment.post.title %></td>
        </tr>
        <tr>
          <th scope="row"><%= Comment.human_attribute_name(:user) %></th>
          <td><%= @comment.user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= Comment.human_attribute_name(:body) %></th>
          <td><%= @comment.body %></td>
        </tr>
        <tr>
          <th scope="row"><%= Comment.human_attribute_name(:created_at) %></th>
          <td><%= l @comment.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>

app/views/admins/comments/update.html.erb
<h1>Admins::Comments#update</h1>
<p>Find me in app/views/admins/comments/update.html.erb</p>