config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'static_pages#top'
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/v1/auth/registrations',
    sessions: 'api/v1/auth/sessions'
  }
  devise_scope :user do
    post 'auth/guest_sign_in', to: 'api/v1/auth/sessions#guest_sign_in'
  end
  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show create] do
        get :search, on: :collection
      end
      resources :postings, only: %i[index show update destroy]
      resources :likes, only: %i[index create destroy] do 
        get :favorites, on: :collection
      end
      resources :comments, only: %i[index create update destroy]
      resource :profiles, only: %i[] do
        get :mypage, on: :collection
        get '/:username', to: 'profiles#show'
      end
    end
  end

  devise_for :admins, skip: %i[registrations passoword], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :posts
    resources :comments
  end

  get '*path', to: 'static_pages#top'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  provider               :string           default("email"), not null
#  uid                    :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  allow_password_change  :boolean          default(FALSE)
#  remember_created_at    :datetime
#  name                   :string           not null
#  email                  :string           not null
#  status                 :integer          default("not_set"), not null
#  prefecture             :integer          default("未設定"), not null
#  self_introduction      :text
#  tokens                 :json
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include DeviseTokenAuth::Concerns::User

  validates :name, { presence: true, uniqueness: true }
  validates :email, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, through: :likes, source: :post

  enum status: { not_set: 0, elementary_school_principal: 1, junior_high_school_principal: 2, former_elementary_school_principal: 3, former_junior_high_school_principal: 4 },
       _prefix: true
  enum prefecture: { 未設定: 0,
                     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
                     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
                     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
                     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
                     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
                     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
                     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
                     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
                     沖縄県: 47 }, _prefix: true

  # ゲストユーザーが存在しない場合、ゲストユーザーを作成
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController
  before_action :find_user, only: %i[show edit update destroy]

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user), success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admins_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :status, :prefecture, :self_introduction)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/admins/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.status_i18n %>
  </td>
  <td>
    <%= l user.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admins_user_path(user), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admins_user_path(user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admins_user_path(user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admins/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= form_with model: @user, url: admins_user_path(@user), local: true do |f| %>
      <%= render 'admins/shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :self_introduction %>
        <%= f.text_field :self_introduction, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :status %>
        <%= f.select :status, User.statuses_i18n.invert, {}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :prefecture %>
        <%= f.select :prefecture, User.prefectures_i18n.invert, {}, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col"><%= User.human_attribute_name(:id) %></th>
            <th scope="col"><%= User.human_attribute_name(:name) %></th>
            <th scope="col"><%= User.human_attribute_name(:status) %></th>
            <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admins/users/new.html.erb
<h1>Admins::Users#new</h1>
<p>Find me in app/views/admins/users/new.html.erb</p>

app/views/admins/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admins_user_path(@user), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admins_user_path(@user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:id) %></th>
          <td><%= @user.id %></td>
        </tr>

        <tr>
          <th scope="row"><%= User.human_attribute_name(:name) %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:self_introduction) %></th>
          <td><%= @user.self_introduction %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:status) %></th>
          <td><%= @user.status_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%=  User.human_attribute_name(:prefecture) %></th>
          <td><%= @user.prefecture %></td>
        </tr>

        <tr>
          <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
          <td><%= l @user.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>