config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'static_pages#top'
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/v1/auth/registrations',
    sessions: 'api/v1/auth/sessions'
  }
  devise_scope :user do
    post 'auth/guest_sign_in', to: 'api/v1/auth/sessions#guest_sign_in'
  end
  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show create] do
        get :search, on: :collection
      end
      resources :postings, only: %i[index show update destroy]
      resources :likes, only: %i[index create destroy] do 
        get :favorites, on: :collection
      end
      resources :comments, only: %i[index create update destroy]
      resource :profiles, only: %i[] do
        get :mypage, on: :collection
        get '/:username', to: 'profiles#show'
      end
    end
  end

  devise_for :admins, skip: %i[registrations passoword], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :posts
    resources :comments
  end

  get '*path', to: 'static_pages#top'
end

app/views/admins/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/admins/shared/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">

      <%= link_to t('defaults.logout'),  destroy_admin_session_path, class: 'nav-link', method: :delete %>

    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/admins/shared/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to admins_root_path, class: "brand-link" do %>
  <%= image_tag 'AdminLTELogo.png', class: 'brand-image img-circle elevation-3' %>
  <span class="brand-text font-weight-light">管理者画面</span>
  <% end %>


  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <%
=begin%>
      <div class="image">
        <%= image_tag current_user.avatar_url, class: 'img-circle elevation-2' %>
      </div>
      <%
=end%>
      <div class="info">
        <a href="#" class="d-block"><%= current_admin.email %></a>
      </div>
    </div>



    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">

          <%= link_to admins_posts_path, class: "nav-link #{active_if('admins/posts')}" do %>
          <i class="nav-icon far fa-file"></i>
          <p>
            講話
          </p>
          <% end %>
        </li>
        <li class="nav-item">

          <%= link_to admins_users_path, class: "nav-link #{active_if('admins/users')}"  do %>
          <i class="nav-icon far fa-user"></i>
          <p>
            ユーザー
          </p>
          <% end %>
        </li>
        <li class="nav-item">

          <%= link_to admins_comments_path, class: "nav-link #{active_if('admins/comments')}"  do %>
          <i class="nav-icon far fa-comment"></i>
          <p>
            コメント
          </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>