config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'static_pages#top'
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/v1/auth/registrations',
    sessions: 'api/v1/auth/sessions'
  }
  devise_scope :user do
    post 'auth/guest_sign_in', to: 'api/v1/auth/sessions#guest_sign_in'
  end
  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show create] do
        get :search, on: :collection
      end
      resources :postings, only: %i[index show update destroy]
      resources :likes, only: %i[index create destroy] do 
        get :favorites, on: :collection
      end
      resources :comments, only: %i[index create update destroy]
      resource :profiles, only: %i[] do
        get :mypage, on: :collection
        get '/:username', to: 'profiles#show'
      end
    end
  end

  devise_for :admins, skip: %i[registrations passoword], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :posts
    resources :comments
  end

  get '*path', to: 'static_pages#top'
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::BaseController  
  def index; end
end

app/helpers/admins/dashboards_helper.rb
module Admins::DashboardsHelper
end

app/views/admins/dashboards/index.html.erb
<div class="container">
  <div class="row">
    <%
=begin%>
 <% if admin_signed_in? %>
    <ul>
      <li><%= current_admin.email %></li>
      <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "ログイン", new_admin_session_path %></li>
    </ul>
    <% end %> 
<%
=end%>
  </div>
</div>  
  